// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: github.com/moby/buildkit/api/services/cache/cache.proto

package moby_buildkit_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheManager_Initialize_FullMethodName  = "/moby.buildkit.v1.cache.CacheManager/Initialize"
	CacheManager_Query_FullMethodName       = "/moby.buildkit.v1.cache.CacheManager/Query"
	CacheManager_Records_FullMethodName     = "/moby.buildkit.v1.cache.CacheManager/Records"
	CacheManager_Record_FullMethodName      = "/moby.buildkit.v1.cache.CacheManager/Record"
	CacheManager_Import_FullMethodName      = "/moby.buildkit.v1.cache.CacheManager/Import"
	CacheManager_LayerInfo_FullMethodName   = "/moby.buildkit.v1.cache.CacheManager/LayerInfo"
	CacheManager_LayerGet_FullMethodName    = "/moby.buildkit.v1.cache.CacheManager/LayerGet"
	CacheManager_LayerUpload_FullMethodName = "/moby.buildkit.v1.cache.CacheManager/LayerUpload"
	CacheManager_LayerCommit_FullMethodName = "/moby.buildkit.v1.cache.CacheManager/LayerCommit"
)

// CacheManagerClient is the client API for CacheManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheManagerClient interface {
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Records(ctx context.Context, in *RecordsRequest, opts ...grpc.CallOption) (*RecordsResponse, error)
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error)
	LayerInfo(ctx context.Context, in *LayerInfoRequest, opts ...grpc.CallOption) (*LayerInfoResponse, error)
	LayerGet(ctx context.Context, in *LayerGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BytesMessage], error)
	LayerUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BytesMessage, LayerUploadResponse], error)
	LayerCommit(ctx context.Context, in *LayerCommitRequest, opts ...grpc.CallOption) (*LayerCommitResponse, error)
}

type cacheManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheManagerClient(cc grpc.ClientConnInterface) CacheManagerClient {
	return &cacheManagerClient{cc}
}

func (c *cacheManagerClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, CacheManager_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheManagerClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, CacheManager_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheManagerClient) Records(ctx context.Context, in *RecordsRequest, opts ...grpc.CallOption) (*RecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordsResponse)
	err := c.cc.Invoke(ctx, CacheManager_Records_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheManagerClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, CacheManager_Record_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheManagerClient) Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportResponse)
	err := c.cc.Invoke(ctx, CacheManager_Import_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheManagerClient) LayerInfo(ctx context.Context, in *LayerInfoRequest, opts ...grpc.CallOption) (*LayerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayerInfoResponse)
	err := c.cc.Invoke(ctx, CacheManager_LayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheManagerClient) LayerGet(ctx context.Context, in *LayerGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BytesMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CacheManager_ServiceDesc.Streams[0], CacheManager_LayerGet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LayerGetRequest, BytesMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CacheManager_LayerGetClient = grpc.ServerStreamingClient[BytesMessage]

func (c *cacheManagerClient) LayerUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BytesMessage, LayerUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CacheManager_ServiceDesc.Streams[1], CacheManager_LayerUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BytesMessage, LayerUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CacheManager_LayerUploadClient = grpc.ClientStreamingClient[BytesMessage, LayerUploadResponse]

func (c *cacheManagerClient) LayerCommit(ctx context.Context, in *LayerCommitRequest, opts ...grpc.CallOption) (*LayerCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayerCommitResponse)
	err := c.cc.Invoke(ctx, CacheManager_LayerCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheManagerServer is the server API for CacheManager service.
// All implementations should embed UnimplementedCacheManagerServer
// for forward compatibility.
type CacheManagerServer interface {
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Records(context.Context, *RecordsRequest) (*RecordsResponse, error)
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
	Import(context.Context, *ImportRequest) (*ImportResponse, error)
	LayerInfo(context.Context, *LayerInfoRequest) (*LayerInfoResponse, error)
	LayerGet(*LayerGetRequest, grpc.ServerStreamingServer[BytesMessage]) error
	LayerUpload(grpc.ClientStreamingServer[BytesMessage, LayerUploadResponse]) error
	LayerCommit(context.Context, *LayerCommitRequest) (*LayerCommitResponse, error)
}

// UnimplementedCacheManagerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheManagerServer struct{}

func (UnimplementedCacheManagerServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedCacheManagerServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedCacheManagerServer) Records(context.Context, *RecordsRequest) (*RecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Records not implemented")
}
func (UnimplementedCacheManagerServer) Record(context.Context, *RecordRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedCacheManagerServer) Import(context.Context, *ImportRequest) (*ImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedCacheManagerServer) LayerInfo(context.Context, *LayerInfoRequest) (*LayerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LayerInfo not implemented")
}
func (UnimplementedCacheManagerServer) LayerGet(*LayerGetRequest, grpc.ServerStreamingServer[BytesMessage]) error {
	return status.Errorf(codes.Unimplemented, "method LayerGet not implemented")
}
func (UnimplementedCacheManagerServer) LayerUpload(grpc.ClientStreamingServer[BytesMessage, LayerUploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method LayerUpload not implemented")
}
func (UnimplementedCacheManagerServer) LayerCommit(context.Context, *LayerCommitRequest) (*LayerCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LayerCommit not implemented")
}
func (UnimplementedCacheManagerServer) testEmbeddedByValue() {}

// UnsafeCacheManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheManagerServer will
// result in compilation errors.
type UnsafeCacheManagerServer interface {
	mustEmbedUnimplementedCacheManagerServer()
}

func RegisterCacheManagerServer(s grpc.ServiceRegistrar, srv CacheManagerServer) {
	// If the following call pancis, it indicates UnimplementedCacheManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheManager_ServiceDesc, srv)
}

func _CacheManager_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheManager_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheManager_Records_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).Records(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_Records_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).Records(ctx, req.(*RecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheManager_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_Record_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheManager_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_Import_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).Import(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheManager_LayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).LayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_LayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).LayerInfo(ctx, req.(*LayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheManager_LayerGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LayerGetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheManagerServer).LayerGet(m, &grpc.GenericServerStream[LayerGetRequest, BytesMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CacheManager_LayerGetServer = grpc.ServerStreamingServer[BytesMessage]

func _CacheManager_LayerUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CacheManagerServer).LayerUpload(&grpc.GenericServerStream[BytesMessage, LayerUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CacheManager_LayerUploadServer = grpc.ClientStreamingServer[BytesMessage, LayerUploadResponse]

func _CacheManager_LayerCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayerCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheManagerServer).LayerCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheManager_LayerCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheManagerServer).LayerCommit(ctx, req.(*LayerCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheManager_ServiceDesc is the grpc.ServiceDesc for CacheManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moby.buildkit.v1.cache.CacheManager",
	HandlerType: (*CacheManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _CacheManager_Initialize_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _CacheManager_Query_Handler,
		},
		{
			MethodName: "Records",
			Handler:    _CacheManager_Records_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _CacheManager_Record_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _CacheManager_Import_Handler,
		},
		{
			MethodName: "LayerInfo",
			Handler:    _CacheManager_LayerInfo_Handler,
		},
		{
			MethodName: "LayerCommit",
			Handler:    _CacheManager_LayerCommit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LayerGet",
			Handler:       _CacheManager_LayerGet_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LayerUpload",
			Handler:       _CacheManager_LayerUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/moby/buildkit/api/services/cache/cache.proto",
}
