// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: github.com/moby/buildkit/api/services/cache/cache.proto

package moby_buildkit_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Deps          []*CacheKeyWithSelector `protobuf:"bytes,1,rep,name=deps,proto3" json:"deps,omitempty"`
	Digest        string                  `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	InputIndex    int32                   `protobuf:"varint,3,opt,name=input_index,json=inputIndex,proto3" json:"input_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetDeps() []*CacheKeyWithSelector {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *QueryRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *QueryRequest) GetInputIndex() int32 {
	if x != nil {
		return x.InputIndex
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheKeys     []string               `protobuf:"bytes,1,rep,name=cache_keys,json=cacheKeys,proto3" json:"cache_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetCacheKeys() []string {
	if x != nil {
		return x.CacheKeys
	}
	return nil
}

type RecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsRequest) Reset() {
	*x = RecordsRequest{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsRequest) ProtoMessage() {}

func (x *RecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsRequest.ProtoReflect.Descriptor instead.
func (*RecordsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{2}
}

func (x *RecordsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*CacheRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsResponse) Reset() {
	*x = RecordsResponse{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsResponse) ProtoMessage() {}

func (x *RecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsResponse.ProtoReflect.Descriptor instead.
func (*RecordsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{3}
}

func (x *RecordsResponse) GetRecords() []*CacheRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{4}
}

func (x *RecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layers        []*CacheLayer          `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{5}
}

func (x *RecordResponse) GetLayers() []*CacheLayer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type LayerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerInfoRequest) Reset() {
	*x = LayerInfoRequest{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerInfoRequest) ProtoMessage() {}

func (x *LayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerInfoRequest.ProtoReflect.Descriptor instead.
func (*LayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{6}
}

func (x *LayerInfoRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type LayerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         *CacheLayer            `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerInfoResponse) Reset() {
	*x = LayerInfoResponse{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerInfoResponse) ProtoMessage() {}

func (x *LayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerInfoResponse.ProtoReflect.Descriptor instead.
func (*LayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{7}
}

func (x *LayerInfoResponse) GetLayer() *CacheLayer {
	if x != nil {
		return x.Layer
	}
	return nil
}

type LayerGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerGetRequest) Reset() {
	*x = LayerGetRequest{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerGetRequest) ProtoMessage() {}

func (x *LayerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerGetRequest.ProtoReflect.Descriptor instead.
func (*LayerGetRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{8}
}

func (x *LayerGetRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *LayerGetRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LayerUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerUploadResponse) Reset() {
	*x = LayerUploadResponse{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerUploadResponse) ProtoMessage() {}

func (x *LayerUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerUploadResponse.ProtoReflect.Descriptor instead.
func (*LayerUploadResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{9}
}

func (x *LayerUploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LayerUploadResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type LayerCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerCommitRequest) Reset() {
	*x = LayerCommitRequest{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerCommitRequest) ProtoMessage() {}

func (x *LayerCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerCommitRequest.ProtoReflect.Descriptor instead.
func (*LayerCommitRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{10}
}

func (x *LayerCommitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LayerCommitRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type LayerCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerCommitResponse) Reset() {
	*x = LayerCommitResponse{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerCommitResponse) ProtoMessage() {}

func (x *LayerCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerCommitResponse.ProtoReflect.Descriptor instead.
func (*LayerCommitResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{11}
}

type CacheKeyWithSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheKeyWithSelector) Reset() {
	*x = CacheKeyWithSelector{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheKeyWithSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheKeyWithSelector) ProtoMessage() {}

func (x *CacheKeyWithSelector) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheKeyWithSelector.ProtoReflect.Descriptor instead.
func (*CacheKeyWithSelector) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{12}
}

func (x *CacheKeyWithSelector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheKeyWithSelector) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type CacheRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRecord) Reset() {
	*x = CacheRecord{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord) ProtoMessage() {}

func (x *CacheRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord.ProtoReflect.Descriptor instead.
func (*CacheRecord) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{13}
}

func (x *CacheRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CacheLayer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlobDigest       string                 `protobuf:"bytes,1,opt,name=blob_digest,json=blobDigest,proto3" json:"blob_digest,omitempty"`
	ParentBlobDigest string                 `protobuf:"bytes,2,opt,name=parent_blob_digest,json=parentBlobDigest,proto3" json:"parent_blob_digest,omitempty"`
	MediaType        string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	DiffId           string                 `protobuf:"bytes,4,opt,name=diff_id,json=diffId,proto3" json:"diff_id,omitempty"`
	Size             uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheLayer) Reset() {
	*x = CacheLayer{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheLayer) ProtoMessage() {}

func (x *CacheLayer) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheLayer.ProtoReflect.Descriptor instead.
func (*CacheLayer) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{14}
}

func (x *CacheLayer) GetBlobDigest() string {
	if x != nil {
		return x.BlobDigest
	}
	return ""
}

func (x *CacheLayer) GetParentBlobDigest() string {
	if x != nil {
		return x.ParentBlobDigest
	}
	return ""
}

func (x *CacheLayer) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CacheLayer) GetDiffId() string {
	if x != nil {
		return x.DiffId
	}
	return ""
}

func (x *CacheLayer) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CacheLayer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type BytesMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesMessage) Reset() {
	*x = BytesMessage{}
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMessage) ProtoMessage() {}

func (x *BytesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMessage.ProtoReflect.Descriptor instead.
func (*BytesMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP(), []int{15}
}

func (x *BytesMessage) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_moby_buildkit_api_services_cache_cache_proto protoreflect.FileDescriptor

const file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDesc = "" +
	"\n" +
	"7github.com/moby/buildkit/api/services/cache/cache.proto\x12\x16moby.buildkit.v1.cache\"\x89\x01\n" +
	"\fQueryRequest\x12@\n" +
	"\x04deps\x18\x01 \x03(\v2,.moby.buildkit.v1.cache.CacheKeyWithSelectorR\x04deps\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1f\n" +
	"\vinput_index\x18\x03 \x01(\x05R\n" +
	"inputIndex\".\n" +
	"\rQueryResponse\x12\x1d\n" +
	"\n" +
	"cache_keys\x18\x01 \x03(\tR\tcacheKeys\" \n" +
	"\x0eRecordsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x0fRecordsResponse\x12=\n" +
	"\arecords\x18\x01 \x03(\v2#.moby.buildkit.v1.cache.CacheRecordR\arecords\"\x1f\n" +
	"\rRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x0eRecordResponse\x12:\n" +
	"\x06layers\x18\x01 \x03(\v2\".moby.buildkit.v1.cache.CacheLayerR\x06layers\"*\n" +
	"\x10LayerInfoRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\"M\n" +
	"\x11LayerInfoResponse\x128\n" +
	"\x05layer\x18\x01 \x01(\v2\".moby.buildkit.v1.cache.CacheLayerR\x05layer\"A\n" +
	"\x0fLayerGetRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"D\n" +
	"\x13LayerUploadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"<\n" +
	"\x12LayerCommitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"\x15\n" +
	"\x13LayerCommitResponse\"B\n" +
	"\x14CacheKeyWithSelector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\"<\n" +
	"\vCacheRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"\xc6\x01\n" +
	"\n" +
	"CacheLayer\x12\x1f\n" +
	"\vblob_digest\x18\x01 \x01(\tR\n" +
	"blobDigest\x12,\n" +
	"\x12parent_blob_digest\x18\x02 \x01(\tR\x10parentBlobDigest\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x17\n" +
	"\adiff_id\x18\x04 \x01(\tR\x06diffId\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\"\n" +
	"\fBytesMessage\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data2\x99\x02\n" +
	"\fCacheManager\x12T\n" +
	"\x05Query\x12$.moby.buildkit.v1.cache.QueryRequest\x1a%.moby.buildkit.v1.cache.QueryResponse\x12Z\n" +
	"\aRecords\x12&.moby.buildkit.v1.cache.RecordsRequest\x1a'.moby.buildkit.v1.cache.RecordsResponse\x12W\n" +
	"\x06Record\x12%.moby.buildkit.v1.cache.RecordRequest\x1a&.moby.buildkit.v1.cache.RecordResponse2\x85\x03\n" +
	"\fCacheStorage\x12[\n" +
	"\x04Info\x12(.moby.buildkit.v1.cache.LayerInfoRequest\x1a).moby.buildkit.v1.cache.LayerInfoResponse\x12V\n" +
	"\x03Get\x12'.moby.buildkit.v1.cache.LayerGetRequest\x1a$.moby.buildkit.v1.cache.BytesMessage0\x01\x12]\n" +
	"\x06Upload\x12$.moby.buildkit.v1.cache.BytesMessage\x1a+.moby.buildkit.v1.cache.LayerUploadResponse(\x01\x12a\n" +
	"\x06Commit\x12*.moby.buildkit.v1.cache.LayerCommitRequest\x1a+.moby.buildkit.v1.cache.LayerCommitResponseB>Z<github.com/moby/buildkit/api/services/cache;moby_buildkit_v1b\x06proto3"

var (
	file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescOnce sync.Once
	file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescData []byte
)

func file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescGZIP() []byte {
	file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescOnce.Do(func() {
		file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDesc), len(file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDesc)))
	})
	return file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDescData
}

var file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_github_com_moby_buildkit_api_services_cache_cache_proto_goTypes = []any{
	(*QueryRequest)(nil),         // 0: moby.buildkit.v1.cache.QueryRequest
	(*QueryResponse)(nil),        // 1: moby.buildkit.v1.cache.QueryResponse
	(*RecordsRequest)(nil),       // 2: moby.buildkit.v1.cache.RecordsRequest
	(*RecordsResponse)(nil),      // 3: moby.buildkit.v1.cache.RecordsResponse
	(*RecordRequest)(nil),        // 4: moby.buildkit.v1.cache.RecordRequest
	(*RecordResponse)(nil),       // 5: moby.buildkit.v1.cache.RecordResponse
	(*LayerInfoRequest)(nil),     // 6: moby.buildkit.v1.cache.LayerInfoRequest
	(*LayerInfoResponse)(nil),    // 7: moby.buildkit.v1.cache.LayerInfoResponse
	(*LayerGetRequest)(nil),      // 8: moby.buildkit.v1.cache.LayerGetRequest
	(*LayerUploadResponse)(nil),  // 9: moby.buildkit.v1.cache.LayerUploadResponse
	(*LayerCommitRequest)(nil),   // 10: moby.buildkit.v1.cache.LayerCommitRequest
	(*LayerCommitResponse)(nil),  // 11: moby.buildkit.v1.cache.LayerCommitResponse
	(*CacheKeyWithSelector)(nil), // 12: moby.buildkit.v1.cache.CacheKeyWithSelector
	(*CacheRecord)(nil),          // 13: moby.buildkit.v1.cache.CacheRecord
	(*CacheLayer)(nil),           // 14: moby.buildkit.v1.cache.CacheLayer
	(*BytesMessage)(nil),         // 15: moby.buildkit.v1.cache.BytesMessage
}
var file_github_com_moby_buildkit_api_services_cache_cache_proto_depIdxs = []int32{
	12, // 0: moby.buildkit.v1.cache.QueryRequest.deps:type_name -> moby.buildkit.v1.cache.CacheKeyWithSelector
	13, // 1: moby.buildkit.v1.cache.RecordsResponse.records:type_name -> moby.buildkit.v1.cache.CacheRecord
	14, // 2: moby.buildkit.v1.cache.RecordResponse.layers:type_name -> moby.buildkit.v1.cache.CacheLayer
	14, // 3: moby.buildkit.v1.cache.LayerInfoResponse.layer:type_name -> moby.buildkit.v1.cache.CacheLayer
	0,  // 4: moby.buildkit.v1.cache.CacheManager.Query:input_type -> moby.buildkit.v1.cache.QueryRequest
	2,  // 5: moby.buildkit.v1.cache.CacheManager.Records:input_type -> moby.buildkit.v1.cache.RecordsRequest
	4,  // 6: moby.buildkit.v1.cache.CacheManager.Record:input_type -> moby.buildkit.v1.cache.RecordRequest
	6,  // 7: moby.buildkit.v1.cache.CacheStorage.Info:input_type -> moby.buildkit.v1.cache.LayerInfoRequest
	8,  // 8: moby.buildkit.v1.cache.CacheStorage.Get:input_type -> moby.buildkit.v1.cache.LayerGetRequest
	15, // 9: moby.buildkit.v1.cache.CacheStorage.Upload:input_type -> moby.buildkit.v1.cache.BytesMessage
	10, // 10: moby.buildkit.v1.cache.CacheStorage.Commit:input_type -> moby.buildkit.v1.cache.LayerCommitRequest
	1,  // 11: moby.buildkit.v1.cache.CacheManager.Query:output_type -> moby.buildkit.v1.cache.QueryResponse
	3,  // 12: moby.buildkit.v1.cache.CacheManager.Records:output_type -> moby.buildkit.v1.cache.RecordsResponse
	5,  // 13: moby.buildkit.v1.cache.CacheManager.Record:output_type -> moby.buildkit.v1.cache.RecordResponse
	7,  // 14: moby.buildkit.v1.cache.CacheStorage.Info:output_type -> moby.buildkit.v1.cache.LayerInfoResponse
	15, // 15: moby.buildkit.v1.cache.CacheStorage.Get:output_type -> moby.buildkit.v1.cache.BytesMessage
	9,  // 16: moby.buildkit.v1.cache.CacheStorage.Upload:output_type -> moby.buildkit.v1.cache.LayerUploadResponse
	11, // 17: moby.buildkit.v1.cache.CacheStorage.Commit:output_type -> moby.buildkit.v1.cache.LayerCommitResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_github_com_moby_buildkit_api_services_cache_cache_proto_init() }
func file_github_com_moby_buildkit_api_services_cache_cache_proto_init() {
	if File_github_com_moby_buildkit_api_services_cache_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDesc), len(file_github_com_moby_buildkit_api_services_cache_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_github_com_moby_buildkit_api_services_cache_cache_proto_goTypes,
		DependencyIndexes: file_github_com_moby_buildkit_api_services_cache_cache_proto_depIdxs,
		MessageInfos:      file_github_com_moby_buildkit_api_services_cache_cache_proto_msgTypes,
	}.Build()
	File_github_com_moby_buildkit_api_services_cache_cache_proto = out.File
	file_github_com_moby_buildkit_api_services_cache_cache_proto_goTypes = nil
	file_github_com_moby_buildkit_api_services_cache_cache_proto_depIdxs = nil
}
