// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: github.com/moby/buildkit/session/netproxy/netproxy.proto

package netproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_TCP Protocol = 0
	Protocol_UDP Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	Protocol_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{0}
}

type DialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=moby.netproxy.v1.Protocol" json:"protocol,omitempty"`
	Addr          *Address               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Mtu           uint32                 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{0}
}

func (x *DialRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_TCP
}

func (x *DialRequest) GetAddr() *Address {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *DialRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type DialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{1}
}

func (x *DialResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type NetworkPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Packet:
	//
	//	*NetworkPacket_Init
	//	*NetworkPacket_Data
	Packet        isNetworkPacket_Packet `protobuf_oneof:"packet"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPacket) Reset() {
	*x = NetworkPacket{}
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPacket) ProtoMessage() {}

func (x *NetworkPacket) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPacket.ProtoReflect.Descriptor instead.
func (*NetworkPacket) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkPacket) GetPacket() isNetworkPacket_Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *NetworkPacket) GetInit() *InitMessage {
	if x != nil {
		if x, ok := x.Packet.(*NetworkPacket_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *NetworkPacket) GetData() *BytesMessage {
	if x != nil {
		if x, ok := x.Packet.(*NetworkPacket_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isNetworkPacket_Packet interface {
	isNetworkPacket_Packet()
}

type NetworkPacket_Init struct {
	Init *InitMessage `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type NetworkPacket_Data struct {
	Data *BytesMessage `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*NetworkPacket_Init) isNetworkPacket_Packet() {}

func (*NetworkPacket_Data) isNetworkPacket_Packet() {}

type InitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMessage) Reset() {
	*x = InitMessage{}
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMessage) ProtoMessage() {}

func (x *InitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMessage.ProtoReflect.Descriptor instead.
func (*InitMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{4}
}

func (x *InitMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BytesMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesMessage) Reset() {
	*x = BytesMessage{}
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMessage) ProtoMessage() {}

func (x *BytesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMessage.ProtoReflect.Descriptor instead.
func (*BytesMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP(), []int{5}
}

func (x *BytesMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BytesMessage) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_github_com_moby_buildkit_session_netproxy_netproxy_proto protoreflect.FileDescriptor

const file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDesc = "" +
	"\n" +
	"8github.com/moby/buildkit/session/netproxy/netproxy.proto\x12\x10moby.netproxy.v1\"\x86\x01\n" +
	"\vDialRequest\x126\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1a.moby.netproxy.v1.ProtocolR\bprotocol\x12-\n" +
	"\x04addr\x18\x02 \x01(\v2\x19.moby.netproxy.v1.AddressR\x04addr\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\rR\x03mtu\"\x1e\n" +
	"\fDialResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x84\x01\n" +
	"\rNetworkPacket\x123\n" +
	"\x04init\x18\x01 \x01(\v2\x1d.moby.netproxy.v1.InitMessageH\x00R\x04init\x124\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.moby.netproxy.v1.BytesMessageH\x00R\x04dataB\b\n" +
	"\x06packet\"\x1d\n" +
	"\vInitMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\fBytesMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof*\x1c\n" +
	"\bProtocol\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x012\xa6\x01\n" +
	"\fNetworkProxy\x12E\n" +
	"\x04Dial\x12\x1d.moby.netproxy.v1.DialRequest\x1a\x1e.moby.netproxy.v1.DialResponse\x12O\n" +
	"\aConnect\x12\x1f.moby.netproxy.v1.NetworkPacket\x1a\x1f.moby.netproxy.v1.NetworkPacket(\x010\x01B+Z)github.com/moby/buildkit/session/netproxyb\x06proto3"

var (
	file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescOnce sync.Once
	file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescData []byte
)

func file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescGZIP() []byte {
	file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescOnce.Do(func() {
		file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDesc), len(file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDesc)))
	})
	return file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDescData
}

var file_github_com_moby_buildkit_session_netproxy_netproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_moby_buildkit_session_netproxy_netproxy_proto_goTypes = []any{
	(Protocol)(0),         // 0: moby.netproxy.v1.Protocol
	(*DialRequest)(nil),   // 1: moby.netproxy.v1.DialRequest
	(*DialResponse)(nil),  // 2: moby.netproxy.v1.DialResponse
	(*Address)(nil),       // 3: moby.netproxy.v1.Address
	(*NetworkPacket)(nil), // 4: moby.netproxy.v1.NetworkPacket
	(*InitMessage)(nil),   // 5: moby.netproxy.v1.InitMessage
	(*BytesMessage)(nil),  // 6: moby.netproxy.v1.BytesMessage
}
var file_github_com_moby_buildkit_session_netproxy_netproxy_proto_depIdxs = []int32{
	0, // 0: moby.netproxy.v1.DialRequest.protocol:type_name -> moby.netproxy.v1.Protocol
	3, // 1: moby.netproxy.v1.DialRequest.addr:type_name -> moby.netproxy.v1.Address
	5, // 2: moby.netproxy.v1.NetworkPacket.init:type_name -> moby.netproxy.v1.InitMessage
	6, // 3: moby.netproxy.v1.NetworkPacket.data:type_name -> moby.netproxy.v1.BytesMessage
	1, // 4: moby.netproxy.v1.NetworkProxy.Dial:input_type -> moby.netproxy.v1.DialRequest
	4, // 5: moby.netproxy.v1.NetworkProxy.Connect:input_type -> moby.netproxy.v1.NetworkPacket
	2, // 6: moby.netproxy.v1.NetworkProxy.Dial:output_type -> moby.netproxy.v1.DialResponse
	4, // 7: moby.netproxy.v1.NetworkProxy.Connect:output_type -> moby.netproxy.v1.NetworkPacket
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_github_com_moby_buildkit_session_netproxy_netproxy_proto_init() }
func file_github_com_moby_buildkit_session_netproxy_netproxy_proto_init() {
	if File_github_com_moby_buildkit_session_netproxy_netproxy_proto != nil {
		return
	}
	file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes[3].OneofWrappers = []any{
		(*NetworkPacket_Init)(nil),
		(*NetworkPacket_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDesc), len(file_github_com_moby_buildkit_session_netproxy_netproxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_moby_buildkit_session_netproxy_netproxy_proto_goTypes,
		DependencyIndexes: file_github_com_moby_buildkit_session_netproxy_netproxy_proto_depIdxs,
		EnumInfos:         file_github_com_moby_buildkit_session_netproxy_netproxy_proto_enumTypes,
		MessageInfos:      file_github_com_moby_buildkit_session_netproxy_netproxy_proto_msgTypes,
	}.Build()
	File_github_com_moby_buildkit_session_netproxy_netproxy_proto = out.File
	file_github_com_moby_buildkit_session_netproxy_netproxy_proto_goTypes = nil
	file_github_com_moby_buildkit_session_netproxy_netproxy_proto_depIdxs = nil
}
