// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: github.com/moby/buildkit/session/netproxy/netproxy.proto

package netproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkProxy_Dial_FullMethodName    = "/moby.netproxy.v1.NetworkProxy/Dial"
	NetworkProxy_Connect_FullMethodName = "/moby.netproxy.v1.NetworkProxy/Connect"
)

// NetworkProxyClient is the client API for NetworkProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkProxyClient interface {
	Dial(ctx context.Context, in *DialRequest, opts ...grpc.CallOption) (*DialResponse, error)
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NetworkPacket, NetworkPacket], error)
}

type networkProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkProxyClient(cc grpc.ClientConnInterface) NetworkProxyClient {
	return &networkProxyClient{cc}
}

func (c *networkProxyClient) Dial(ctx context.Context, in *DialRequest, opts ...grpc.CallOption) (*DialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DialResponse)
	err := c.cc.Invoke(ctx, NetworkProxy_Dial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkProxyClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NetworkPacket, NetworkPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkProxy_ServiceDesc.Streams[0], NetworkProxy_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NetworkPacket, NetworkPacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkProxy_ConnectClient = grpc.BidiStreamingClient[NetworkPacket, NetworkPacket]

// NetworkProxyServer is the server API for NetworkProxy service.
// All implementations should embed UnimplementedNetworkProxyServer
// for forward compatibility.
type NetworkProxyServer interface {
	Dial(context.Context, *DialRequest) (*DialResponse, error)
	Connect(grpc.BidiStreamingServer[NetworkPacket, NetworkPacket]) error
}

// UnimplementedNetworkProxyServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkProxyServer struct{}

func (UnimplementedNetworkProxyServer) Dial(context.Context, *DialRequest) (*DialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dial not implemented")
}
func (UnimplementedNetworkProxyServer) Connect(grpc.BidiStreamingServer[NetworkPacket, NetworkPacket]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNetworkProxyServer) testEmbeddedByValue() {}

// UnsafeNetworkProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkProxyServer will
// result in compilation errors.
type UnsafeNetworkProxyServer interface {
	mustEmbedUnimplementedNetworkProxyServer()
}

func RegisterNetworkProxyServer(s grpc.ServiceRegistrar, srv NetworkProxyServer) {
	// If the following call pancis, it indicates UnimplementedNetworkProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkProxy_ServiceDesc, srv)
}

func _NetworkProxy_Dial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkProxyServer).Dial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkProxy_Dial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkProxyServer).Dial(ctx, req.(*DialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkProxy_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkProxyServer).Connect(&grpc.GenericServerStream[NetworkPacket, NetworkPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkProxy_ConnectServer = grpc.BidiStreamingServer[NetworkPacket, NetworkPacket]

// NetworkProxy_ServiceDesc is the grpc.ServiceDesc for NetworkProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moby.netproxy.v1.NetworkProxy",
	HandlerType: (*NetworkProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dial",
			Handler:    _NetworkProxy_Dial_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NetworkProxy_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/moby/buildkit/session/netproxy/netproxy.proto",
}
